### ISSUE TITLE
"could not load plugin" after updating Paper (1.21.3-63) and Essentials (2.21.0-dev+141)

### ISSUE THREAD

**Issue by kribjo** [pop4959/BlueMap-Essentials#14]
This error is new after updating Paper from 1.21.3-58 to 1.21.3-63 and EssentialsX from 2.21.0-dev+130 to 2.21.0-dev+141.
ViaVersion was also updated at the same time (5.1.2-SNAPSHOT+625 from 5.1.1 release version), if that could possibly be related.

EssentialsX changelog: https://github.com/EssentialsX/Essentials/commits/2.x
Paper changelog: https://papermc.io/downloads/paper
ViaVersion changelog: https://github.com/ViaVersion/ViaVersion/commits

Error message:
```
[06:28:04 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'BlueMap-Essentials-1.1.3.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/ess3/api/InvalidWorldException
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:561) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/ess3/api/InvalidWorldException
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.ess3.api.InvalidWorldException
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.3.jar:1.21.3-63-4190ee7]
        ... 9 more
```

**Details**
Bluemap version info:
Version: 5.5
Commit: 2c63d767824aa5b5156bcc245aa8d951d4dca782
Implementation: paper

EssentialsX version info:
Server version: 1.21.3-R0.1-SNAPSHOT 1.21.3-63-4190ee7 (MC: 1.21.3)
Brand version: Paper
EssentialsX version: 2.21.0-dev+141-c7cc1b4
LuckPerms version: 5.4.145
Vault version: 1.7.3-b131
PlaceholderAPI version: 2.11.6
EssentialsXSpawn version: 2.21.0-dev+141-c7cc1b4
EssentialsXGeoIP version: 2.21.0-dev+141-c7cc1b4
EssentialsXChat version: 2.21.0-dev+141-c7cc1b4
DiscordSRV version: 1.29.0
Economy Layer: None

Paper version info:
This server is running Paper version 1.21.3-63-master@4190ee7 (2024-11-25T18:59:19Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)

**Comment by RHX0R3** [comment]
*bump*

@pop4959
Can confirm, as of Paper 1.21.1 ([build #132-b48403b](https://api.papermc.io/v2/projects/paper/versions/1.21.1/builds/132/downloads/paper-1.21.1-132.jar)).

Is this a general problem, or is it related to the latest BlueMap update [5.5](https://github.com/BlueMap-Minecraft/BlueMap/releases/tag/v5.5)?

**Comment by pop4959** [comment]
Thanks for the reports, I will try to have time to update this sometime this week. It looks like maybe Essentials changed something. Try using an older build of Essentials as a workaround for now.

**Comment by pop4959** [comment]
This is fixed in Essentials 2.21.0-dev+145-bc8aa76. Download [here](https://essentialsx.net/downloads.html). You do not need to update BlueMap-Essentials.
